Waiting for JIT...
num_batches 4096
0
jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/Users/akshayjacobthomas/Documents/GitHub/DiffMicromehanics/surrogate/main.py", line 40, in <module>
    app.run(main)
  File "/Users/akshayjacobthomas/anaconda3/envs/jax_trial/lib/python3.9/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/Users/akshayjacobthomas/anaconda3/envs/jax_trial/lib/python3.9/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/Users/akshayjacobthomas/Documents/GitHub/DiffMicromehanics/surrogate/main.py", line 32, in main
    train.train_and_evaluate(FLAGS.config, FLAGS.workdir)
  File "/Users/akshayjacobthomas/Documents/GitHub/DiffMicromehanics/surrogate/train.py", line 81, in train_and_evaluate
    model.state = model.step(model.state, batch)
  File "/Users/akshayjacobthomas/Documents/GitHub/DiffMicromehanics/surrogate/NN_surrogate/models.py", line 170, in step
    grads = grad(self.loss)(state.params, state.weights,batch,*args)
  File "/Users/akshayjacobthomas/Documents/GitHub/DiffMicromehanics/surrogate/NN_surrogate/models.py", line 127, in loss
    losses = self.losses(params, batch, *args)
  File "/Users/akshayjacobthomas/Documents/GitHub/DiffMicromehanics/surrogate/models.py", line 40, in losses
    mse_loss = jnp.mean(vmap(self.residual, (None, 0, 0)))(params, x, y_actual)
  File "/Users/akshayjacobthomas/anaconda3/envs/jax_trial/lib/python3.9/site-packages/jax/_src/numpy/reductions.py", line 323, in mean
    return _mean(a, _ensure_optional_axes(axis), dtype, out, keepdims,
TypeError: Cannot interpret value of type <class 'function'> as an abstract array; it does not have a dtype attribute